#!/usr/bin/env bash
# Gtk-Omarchy-Theme-Inheritar installer.
#
# Installs the generator, the theme-set hooks and the user-local Nautilus
# extension, then generates the current theme immediately. Idempotent: running
# it twice changes nothing and never duplicates hooks or extensions. Nothing is
# written outside the user's home directory.
set -euo pipefail

PROJECT="Gtk-Omarchy-Theme-Inheritar"
REPO_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
MARKER="Generated by ${PROJECT}"

XDG_BIN="${HOME}/.local/bin"
XDG_STATE="${XDG_STATE_HOME:-${HOME}/.local/state}"
XDG_DATA="${XDG_DATA_HOME:-${HOME}/.local/share}"
HOOK_DIR="${HOME}/.config/omarchy/hooks/theme-set.d"
EXT_DIR="${XDG_DATA}/nautilus-python/extensions"
STATE_DIR="${XDG_STATE}/gtk-omarchy-theme-inheritar"
STATE_FILE="${STATE_DIR}/install.json"

GENERATOR_SRC="${REPO_DIR}/bin/omarchy-adwaita-gtk"
GENERATOR_DST="${XDG_BIN}/omarchy-adwaita-gtk"

log()  { printf '  %s\n' "$*"; }
warn() { printf '  warning: %s\n' "$*" >&2; }
die()  { printf 'error: %s\n' "$*" >&2; exit 1; }

installed_paths=()
record() { installed_paths+=("$1"); }

is_ours() { # file → 0 when it carries our marker (current or earlier revision)
    [ -f "$1" ] || return 1
    grep -q "$MARKER" "$1" 2>/dev/null && return 0
    grep -q "Generated by omarchy-adwaita-gtk" "$1" 2>/dev/null
}

equivalent_ignoring_comments() { # a b → 0 when both carry the same code
    diff -q <(grep -vE '^[[:space:]]*(#|$)' "$1") \
            <(grep -vE '^[[:space:]]*(#|$)' "$2") >/dev/null 2>&1
}

install_file() { # src dst label
    local src="$1" dst="$2" label="$3"
    mkdir -p "$(dirname "$dst")"
    if [ -f "$dst" ]; then
        if cmp -s "$src" "$dst"; then
            log "${label}: already present, identical"
            record "$dst"
            return 0
        fi
        if equivalent_ignoring_comments "$src" "$dst"; then
            # Same code, different comments: for example a copy installed by the
            # paint-omarchy-nautilus package, which ships this hook verbatim.
            log "${label}: already present (equivalent to the shipped copy), kept"
            record "$dst"
            return 0
        fi
        if is_ours "$dst"; then
            install -m 644 "$src" "$dst"
            log "${label}: updated"
            record "$dst"
            return 0
        fi
        local backup="${dst}.pre-gtk-omarchy-theme-inheritar"
        if [ -e "$backup" ]; then
            warn "${label}: foreign file kept (backup already at ${backup})"
        else
            cp -p "$dst" "$backup"
            warn "${label}: foreign file backed up to ${backup} and left untouched"
        fi
        return 0
    fi
    install -m 644 "$src" "$dst"
    log "${label}: installed"
    record "$dst"
}

echo "${PROJECT} installer"
echo
echo "1. Environment"

command -v python3 >/dev/null || die "python3 is required"
command -v gsettings >/dev/null || die "gsettings (glib2) is required"
command -v gresource >/dev/null || warn "gresource not found; the generator will fall back to PyGObject"

if [ -n "${OMARCHY_PATH:-}" ] || [ -d /usr/share/omarchy ] || command -v omarchy >/dev/null; then
    log "Omarchy: detected"
else
    die "Omarchy not detected (no \$OMARCHY_PATH, /usr/share/omarchy or omarchy command)"
fi

RESOLVER=""
for candidate in "${OMARCHY_PATH:-/usr/share/omarchy}/bin/omarchy-theme-color" \
                 /usr/share/omarchy/bin/omarchy-theme-color \
                 "$(command -v omarchy-theme-color 2>/dev/null || true)"; do
    [ -n "$candidate" ] && [ -x "$candidate" ] && RESOLVER="$candidate" && break
done
[ -n "$RESOLVER" ] || die "omarchy-theme-color not found (required palette resolver)"
log "palette resolver: ${RESOLVER}"

if [ -f "${XDG_STATE}/omarchy/current/theme/colors.toml" ]; then
    log "active theme: $(cat "${XDG_STATE}/omarchy/current/theme.name" 2>/dev/null || echo '?')"
else
    warn "no staged Omarchy theme found yet; run 'omarchy theme set <theme>' first"
fi

if command -v pacman >/dev/null; then
    for pkg in gtk3 gtk4 libadwaita libhandy nautilus nautilus-python; do
        version=$(pacman -Q "$pkg" 2>/dev/null | awk '{print $2}')
        [ -n "$version" ] && log "${pkg}: ${version}" || warn "${pkg}: not installed"
    done
fi

if [ -e /usr/lib/nautilus/extensions-4/libnautilus-python.so ] \
   || [ -e /usr/lib/nautilus/extensions-3.0/libnautilus-python.so ]; then
    log "nautilus-python: present"
else
    cat >&2 <<'EOF'
error: nautilus-python is required for Gtk-Omarchy-Theme-Inheritar's specialized
       Nautilus palette and live-reload layer, and it was not found.

       Install it with:
           sudo pacman -S nautilus-python

       Then run ./install.sh again.

       Nothing has been installed or modified.
EOF
    exit 1
fi

echo
echo "2. Files"

install -m 755 "$GENERATOR_SRC" "$GENERATOR_DST"
log "generator: installed at ${GENERATOR_DST}"
record "$GENERATOR_DST"

install_file "${REPO_DIR}/hooks/60-omarchy-gtk-accent.sh" \
             "${HOOK_DIR}/60-omarchy-gtk-accent.sh" "hook 60 (Omarchy accent)"
install_file "${REPO_DIR}/hooks/70-omarchy-nautilus-palette.sh" \
             "${HOOK_DIR}/70-omarchy-nautilus-palette.sh" "hook 70 (Nautilus palette)"
install_file "${REPO_DIR}/hooks/80-omarchy-adwaita-gtk.sh" \
             "${HOOK_DIR}/80-omarchy-adwaita-gtk.sh" "hook 80 (GTK inheritance)"
chmod +x "${HOOK_DIR}/60-omarchy-gtk-accent.sh" "${HOOK_DIR}/70-omarchy-nautilus-palette.sh" \
         "${HOOK_DIR}/80-omarchy-adwaita-gtk.sh" 2>/dev/null || true

if [ -f /usr/share/nautilus-python/extensions/omarchy_palette.py ]; then
    log "Nautilus extension: already provided by a system package, not duplicating it"
    log "                     (${PROJECT} relies on it; see docs/NAUTILUS.md)"
elif [ -f "${EXT_DIR}/omarchy_palette.py" ]; then
    install_file "${REPO_DIR}/nautilus/omarchy_palette.py" \
                 "${EXT_DIR}/omarchy_palette.py" "Nautilus extension (user-local)"
else
    install_file "${REPO_DIR}/nautilus/omarchy_palette.py" \
                 "${EXT_DIR}/omarchy_palette.py" "Nautilus extension (user-local)"
fi

echo
echo "3. Generating the active theme"
"$GENERATOR_DST"

echo
echo "4. Refreshing accent colour and Nautilus palette"
"${HOOK_DIR}/60-omarchy-gtk-accent.sh" "${1:-}" || warn "hook 60 failed"
"${HOOK_DIR}/70-omarchy-nautilus-palette.sh" "${1:-}" || warn "hook 70 failed"

echo
echo "5. State"
mkdir -p "$STATE_DIR"
{
    printf '{\n'
    printf '  "project": "%s",\n' "$PROJECT"
    printf '  "installed": "%s",\n' "$(date -Iseconds)"
    printf '  "repo": "%s",\n' "$REPO_DIR"
    printf '  "paths": [\n'
    last=$((${#installed_paths[@]} - 1))
    for i in "${!installed_paths[@]}"; do
        if [ "$i" -lt "$last" ]; then
            printf '    "%s",\n' "${installed_paths[$i]}"
        else
            printf '    "%s"\n' "${installed_paths[$i]}"
        fi
    done
    printf '  ]\n}\n'
} > "${STATE_FILE}.tmp.$$"
mv "${STATE_FILE}.tmp.$$" "$STATE_FILE"
log "state written to ${STATE_FILE}"

echo
echo "Done. Theme changes now regenerate every layer automatically:"
echo "  60 accent → 70 Nautilus palette → 80 GTK3/GTK4/libadwaita palette"
echo "Remove everything again with: ${REPO_DIR}/uninstall.sh"
