#!/usr/bin/env bash
# Gtk-Omarchy-Theme-Inheritar uninstaller.
#
# Removes exactly what this project owns: the generated theme and user
# stylesheets (through the generator's own --restore), the generator itself,
# hook 80, and - only when this project installed them - hooks 60/70 and the
# user-local Nautilus extension. Foreign files, backups, Lutris, Nautilus
# configuration and unrelated GTK files are never touched.
set -euo pipefail

PROJECT="Gtk-Omarchy-Theme-Inheritar"
REPO_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
MARKER="Generated by ${PROJECT}"

XDG_BIN="${HOME}/.local/bin"
XDG_STATE="${XDG_STATE_HOME:-${HOME}/.local/state}"
XDG_DATA="${XDG_DATA_HOME:-${HOME}/.local/share}"
HOOK_DIR="${HOME}/.config/omarchy/hooks/theme-set.d"
EXT_DIR="${XDG_DATA}/nautilus-python/extensions"
STATE_DIR="${XDG_STATE}/gtk-omarchy-theme-inheritar"
STATE_FILE="${STATE_DIR}/install.json"

log()  { printf '  %s\n' "$*"; }
warn() { printf '  warning: %s\n' "$*" >&2; }

owned_by_state() { # path -> 0 when the install state lists it
    [ -f "$STATE_FILE" ] && grep -q "\"$1\"" "$STATE_FILE"
}

is_ours() {
    [ -f "$1" ] || return 1
    grep -q "$MARKER" "$1" 2>/dev/null && return 0
    grep -q "Generated by omarchy-adwaita-gtk" "$1" 2>/dev/null
}

remove_if_ours() { # path label
    local path="$1" label="$2"
    [ -e "$path" ] || { log "${label}: already absent"; return 0; }
    if is_ours "$path" || owned_by_state "$path"; then
        rm -f "$path"
        log "${label}: removed"
    else
        warn "${label}: not generated by ${PROJECT}, left in place (${path})"
    fi
}

echo "${PROJECT} uninstaller"

if [ -x "${XDG_BIN}/omarchy-adwaita-gtk" ]; then
    log "restoring the previous GTK state"
    "${XDG_BIN}/omarchy-adwaita-gtk" --restore || warn "generator --restore reported an error"
else
    warn "generator not found; removing generated files directly"
    rm -rf "${XDG_DATA}/themes/Omarchy-Adwaita"
    remove_if_ours "${HOME}/.config/gtk-3.0/gtk.css" "GTK3 user stylesheet"
    remove_if_ours "${HOME}/.config/gtk-4.0/gtk.css" "GTK4 user stylesheet"
    rm -f "${HOOK_DIR}/80-omarchy-adwaita-gtk.sh"
    log "hook 80: removed"
fi

remove_if_ours "${XDG_BIN}/omarchy-adwaita-gtk" "generator"

# Hooks 60 and 70 are shared with paint-omarchy-nautilus: only remove them when
# this project installed them (state file) and no upstream copy exists.
for hook in 60-omarchy-gtk-accent.sh 70-omarchy-nautilus-palette.sh; do
    path="${HOOK_DIR}/${hook}"
    if [ -e "$path" ]; then
        if owned_by_state "$path" && ! cmp -s "$path" "/usr/share/paint-omarchy-nautilus/hooks/theme-set.d/${hook}" 2>/dev/null; then
            rm -f "$path"
            log "${hook}: removed (installed by ${PROJECT})"
        else
            log "${hook}: left in place (provided by paint-omarchy-nautilus or a foreign file)"
        fi
    fi
done

if [ -f "${EXT_DIR}/omarchy_palette.py" ] && owned_by_state "${EXT_DIR}/omarchy_palette.py"; then
    if [ -f /usr/share/nautilus-python/extensions/omarchy_palette.py ]; then
        log "Nautilus extension: kept (a system package also provides it)"
    else
        rm -f "${EXT_DIR}/omarchy_palette.py"
        log "Nautilus extension (user-local): removed"
    fi
fi

if [ -d "$STATE_DIR" ]; then
    rm -rf "$STATE_DIR"
    log "state: removed"
fi

echo
echo "Uninstall complete. Restart applications (and Nautilus) to pick up the"
echo "restored Adwaita theme. Generated CSS and the theme directory are gone;"
echo "foreign files and backups were left untouched."
