#!/bin/bash
# Regenerate the libadwaita palette CSS that omarchy_palette.py hot-reloads
# inside running Nautilus processes. Runs on every `omarchy theme set`
# (theme-set.d hook); source of truth is the staged theme's colors.toml.
# Output: ~/.cache/omarchy/gtk/nautilus.css (written atomically).
#
# Part of Gtk-Omarchy-Theme-Inheritar.
# Derived from paint-omarchy-nautilus (MIT, Copyright (c) 2024 JJDizz1L),
# https://github.com/JJDizz1L/paint-omarchy-nautilus -- see LICENSE.

set -u

COLORS_FILE=$HOME/.local/state/omarchy/current/theme/colors.toml
OUT_DIR=$HOME/.cache/omarchy/gtk
OUT_FILE=$OUT_DIR/nautilus.css

[[ -f $COLORS_FILE ]] || exit 0
mkdir -p "$OUT_DIR"

if ! python3 - "$COLORS_FILE" >"$OUT_FILE.tmp.$$" <<'PY'
import os
import sys
import tomllib

with open(sys.argv[1], "rb") as fh:
    c = tomllib.load(fh)


def need(key):
    v = c.get(key)
    if not isinstance(v, str):
        print(f"omarchy-nautilus-palette: colors.toml has no usable '{key}'; skipping", file=sys.stderr)
        sys.exit(1)
    return v.lstrip("#")


def opt(key, fallback):
    v = c.get(key)
    return v.lstrip("#") if isinstance(v, str) else fallback


background = need("background")
foreground = need("foreground")
mode = c.get("mode", "dark")
dark_bg = opt("dark_background", background)
darker_bg = opt("darker_background", dark_bg)
lighter_bg = opt("lighter_background", background)
accent = opt("accent", "3584e4")
muted = opt("muted", foreground)
red = opt("red", "e62d42")
green = opt("green", "3a944a")
yellow = opt("yellow", "c88800")


def rgba(hexstr, alpha):
    r, g, b = (int(hexstr[i:i + 2], 16) for i in (0, 2, 4))
    return f"rgba({r},{g},{b},{alpha})"


def luminance(hexstr):
    def chan(i):
        v = int(hexstr[i:i + 2], 16) / 255
        return v / 12.92 if v <= 0.03928 else ((v + 0.055) / 1.055) ** 2.4
    return 0.2126 * chan(0) + 0.7152 * chan(2) + 0.0722 * chan(4)


accent_fg = "#ffffff" if luminance(accent) < 0.45 else "#" + background

name_file = os.path.expanduser("~/.local/state/omarchy/current/theme.name")
theme_name = open(name_file).read().strip() if os.path.isfile(name_file) else "unknown"

lines = [
    "/* Generated by ~/.config/omarchy/hooks/theme-set.d/70-omarchy-nautilus-palette.sh",
    f"   from Omarchy theme '{theme_name}'. Do not edit; it is overwritten on every theme set. */",
    "",
    f"@define-color window_bg_color #{background};",
    f"@define-color window_fg_color #{foreground};",
    f"@define-color view_bg_color #{background};",
    f"@define-color view_fg_color #{foreground};",
    f"@define-color headerbar_bg_color #{background};",
    f"@define-color headerbar_fg_color #{foreground};",
    f"@define-color headerbar_backdrop_color #{dark_bg};",
    f"@define-color headerbar_shade_color {rgba(muted, 0.36)};",
    f"@define-color headerbar_darker_shade_color {rgba(muted, 0.6)};",
    f"@define-color sidebar_bg_color #{dark_bg};",
    f"@define-color sidebar_fg_color #{foreground};",
    f"@define-color sidebar_backdrop_color #{darker_bg};",
    f"@define-color sidebar_shade_color {rgba(muted, 0.25)};",
    f"@define-color sidebar_border_color {rgba(muted, 0.36)};",
    f"@define-color secondary_sidebar_bg_color #{darker_bg};",
    f"@define-color secondary_sidebar_fg_color #{foreground};",
    f"@define-color secondary_sidebar_backdrop_color #{darker_bg};",
    f"@define-color card_bg_color #{lighter_bg};",
    f"@define-color card_fg_color #{foreground};",
    f"@define-color card_shade_color {rgba(muted, 0.25)};",
    f"@define-color dialog_bg_color #{lighter_bg};",
    f"@define-color dialog_fg_color #{foreground};",
    f"@define-color popover_bg_color #{lighter_bg};",
    f"@define-color popover_fg_color #{foreground};",
    f"@define-color thumbnail_bg_color #{lighter_bg};",
    f"@define-color thumbnail_fg_color #{muted};",
    f"@define-color accent_bg_color #{accent};",
    f"@define-color accent_fg_color {accent_fg};",
    f"@define-color accent_color #{accent};",
    f"@define-color destructive_bg_color #{red};",
    "@define-color destructive_fg_color #ffffff;",
    f"@define-color destructive_color #{red};",
    f"@define-color success_bg_color #{green};",
    "@define-color success_fg_color #ffffff;",
    f"@define-color success_color #{green};",
    f"@define-color warning_bg_color #{yellow};",
    f"@define-color warning_fg_color #{background};",
    f"@define-color warning_color #{yellow};",
    f"@define-color error_bg_color #{red};",
    "@define-color error_fg_color #ffffff;",
    f"@define-color error_color #{red};",
    f"@define-color shade_color {rgba('000000', 0.18 if mode == 'light' else 0.36)};",
    f"@define-color scrollbar_outline_color {'rgba(255,255,255,0.12)' if mode == 'dark' else 'rgba(0,0,0,0.15)'};",
    "",
]
print("\n".join(lines))
PY
then
  rm -f "$OUT_FILE.tmp.$$"
  exit 0
fi

mv "$OUT_FILE.tmp.$$" "$OUT_FILE"
