#!/bin/bash
# Generated by omarchy-adwaita-gtk; do not edit.
#
# Rebuild the system-wide GTK theme from the freshly staged Omarchy palette
# after every `omarchy theme set`, and select it with the normal GSettings
# mechanism. Runs after 60-omarchy-gtk-accent.sh and
# 70-omarchy-nautilus-palette.sh, neither of which it touches.

set -u

"$HOME/.local/bin/omarchy-adwaita-gtk" --quiet
